# Prefix: Ctrl+a
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Window navigation
bind -r H previous-window
bind -r L next-window
bind Tab last-window
bind Enter copy-mode

# Splits like Neovim
unbind %
unbind '"'
bind v split-window -h
bind s split-window -v

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
if-shell '[ "$TERMINAL_EMULATOR" = "JetBrains-JediTerm" ]' 'set -g default-terminal "screen-256color"'

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -ga update-environment "TERMINAL_EMULATOR"
set -g allow-passthrough off

set -s escape-time 0

# Vi copy mode
set -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"

# Mouse support
set -g mouse on
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection -x
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -xPrefix: Ctrl+a
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Window navigation
bind -r H previous-window
bind -r L next-window
bind Tab last-window

# Splits like Neovim
unbind %
unbind '"'
bind v split-window -h
bind s split-window -v

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
if-shell '[ "$TERMINAL_EMULATOR" = "JetBrains-JediTerm" ]' 'set -g default-terminal "screen-256color"'

set -g pane-border-status top
set -g pane-border-format '#{?pane_in_mode,#[fg=black,bg=yellow,bold] COPY ,} #P #{pane_current_command}'

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -ga update-environment "TERMINAL_EMULATOR"
set -g allow-passthrough off

set -s escape-time 0

# Vi copy mode
set -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"

# Mouse support
set -g mouse on
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection -x
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection -x
