#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed gimp tldr go fzf rofi-wayland btop bc stylua
go install github.com/air-verse/air@latest
sudo pacman -S love --noconfirm --needed
sudo pacman -S ttf-font-awesome waybar ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols --noconfirm --needed
sudo pacman -S hyprlock --noconfirm --needed
sudo pacman -S hyprpaper --noconfirm --needed
sudo pacman -S ghostty --noconfirm --needed
sudo pacman -S hyprpaper hyprshot --noconfirm --needed
sudo pacman -S pavucontrol --noconfirm --needed
sudo pacman -S rsync --noconfirm --needed
paru -Syu wlogout-git --noconfirm --needed

curl -sS https://starship.rs/install.sh | sh
