#!/usr/bin/env bash
set -euo pipefail

: "${DEV_ENV:?DEV_ENV is not set}"
cd "$DEV_ENV"

DEV_ENV="$PWD" ./dev-env

pkill -x waybar || true
pkill -x hyprpaper || true
sleep 0.2
nohup hyprpaper &>/dev/null &
nohup waybar &>/dev/null &
disown -a
